### ISSUE TITLE
502 Bad Gateway h5ai

### ISSUE THREAD

**Issue by bilyboy785** [PixiBixi/dockerfiles#1]
Hi ! 

I've got an error with your h5ai docker : 502 bad gateway. 

I've got [that ](https://paste.bouillaudmartin.fr/?62588d7c1e8e2432#N2ZbCMziPxRI2lKCpAOGA+QVb4nYkHhAt0mtZ+R/Nu8=) in logs

**Comment by PixiBixi** [comment]
Yop, intéressant, pourtant il marche

Perso j'ai ça en docker-compose : 

```
  x_h5ai:
    image: bixidock/h5ai
    restart: always
    container_name: x_h5ai
    volumes:
      - /home/x/incoming/torrents:/var/www
    environment:
      - VIRTUAL_HOST=share.x.y.eu
      - LETSENCRYPT_EMAIL=contact@y.eu
      - LETSENCRYPT_HOST=share.x.y.eu
```

Tu as quoi comme compose ?

**Comment by bilyboy785** [comment]
J'ai à peu près la même chose : 

```
h5ai-martin:
    restart: always
    image: bixidock/h5ai
    container_name: h5ai-martin
    ports:
      - 5055:80
    volumes:
      - /home/user/data:/var/www
      - /home/martinbouillaud/dockers/h5ai/options.json:/usr/share/h5ai/_h5ai/private/conf/options.json
    environment:
      - VIRTUAL_HOST=sub.domain.tld
      - LETSENCRYPT_HOST=sub.domain.tld
      - LETSENCRYPT_EMAIL=mail@domain.tld
```

Dois-je retirer la ligne **port** ?

**Comment by PixiBixi** [comment]
Ouep, essaie ça, et en enlevant von volumes options.json surtout

**Comment by bilyboy785** [comment]
Non toujours pareille.

```
BusyBox v1.24.2 (2017-01-18 14:13:46 GMT) multi-call binary.

Usage: addgroup [-g GID] [-S] [USER] GROUP

Add a group or add a user to a group

	-g GID	Group id
	-S	Create a system group
chown: unknown user/group dokuwiki:dokuwiki
2017-11-21 19:42:50,156 CRIT Supervisor running as root (no user in config file)
2017-11-21 19:42:50,158 INFO supervisord started with pid 10
2017-11-21 19:42:51,160 INFO spawned: 'nginx' with pid 14
2017-11-21 19:42:51,161 INFO spawned: 'php-fpm' with pid 15
2017-11-21 19:42:51,175 INFO exited: php-fpm (exit status 127; not expected)
2017-11-21 19:42:52,177 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-21 19:42:52,179 INFO spawned: 'php-fpm' with pid 20
2017-11-21 19:42:52,188 INFO exited: php-fpm (exit status 127; not expected)
2017-11-21 19:42:54,191 INFO spawned: 'php-fpm' with pid 21
2017-11-21 19:42:54,200 INFO exited: php-fpm (exit status 127; not expected)
```

Bizarre que ça fasse ça d'un coup .. Ca a toujours très bien marché.

**Comment by PixiBixi** [comment]
Mmmh c'est clair.. je regarde plus en détail demain soir, j'ai pas le temps là... 

Si encore j'utilsais alpine:edge, j'aurais pu comprendre, mais là j'suis bien en alpine:3.4...

**Comment by bilyboy785** [comment]
Pas de soucis, je vais faire des tests avec FileRun en attendant ;)

**Comment by PixiBixi** [comment]
J'ai check un peu, et c'est juste bizarre quoi ><"

Essaie de mettre UID=1001 et GID=1001 en variable d'env mais ça va rien changer

**Comment by bilyboy785** [comment]
Pareille .. J'ai mis 1000 parce que j'ai aucun user en 1001. Je vais me tourner vers Filerun ou Explorer.

**Comment by PixiBixi** [comment]
Plop

Tu peux vérifier que c'est ok ? :)

PS: L'image utilise maintenant le port 8080

**Comment by bilyboy785** [comment]
Toujours pas ..

![](https://dsc.cloud/martinbouillaud/Screen-Shot-2017-12-09-18-08-34/Screen-Shot-2017-12-09-18-08-34.png)

**Comment by PixiBixi** [comment]
Pense à MAJ l'image : docker pull bixidock/h5ai

Tu as bien fais un docker-compose up -d ? (j'ai testé et ça marche, donc bon :D) 

Fait moi voir ton docker-compose.yml

PS: J'ai lancé l'image avec cette ligne pour mes tests : 

```
docker run -it --rm -p 12345:8080 -v /root/dockerfiles/h5ai/lel:/var/www bixidock/h5ai
```

**Comment by bilyboy785** [comment]
```
h5ai-martin:
    restart: always
    image: bixidock/h5ai
    container_name: h5ai-martin
    ports:
      - 5055:8080
    volumes:
      - /home/martinbouillaud/data:/var/www
    environment:
      - VIRTUAL_HOST=h5.*****.com
      - LETSENCRYPT_HOST=h5.*****.com
      - LETSENCRYPT_EMAIL=contact@*****
```
